### ISSUE TITLE
User can view a list of anime titles that match their search query

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#1]
## 📐 Functionality

User can search for an anime by title and a list of all anime matching the query will be displayed.  Each matching result will show the cover art, anime title, rating, air date, and genres.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/156668188-c25904f9-2573-4c16-8da7-0ae7f31595e4.png)
![image](https://user-images.githubusercontent.com/48267398/156668218-70ce5797-89b7-4c51-be66-8273439f7f2e.png)

## ✅ Task List

- [x]  Add welcome message to body of html doc
- [x]  Add navigation bar div to html
- [x]  Add home icon to nav bar 
- [x]  Add input element to the nav bar to act as search bar
- [x]  add magnifying glass icon to search bar
- [x]  Create HTML template for each list item for anime results
- [x]  Create function that will add to the DOM tree for each result
- [x]  Call DOM tree function to display every result that was received from the server
    - [x] store the data into an object in a data.js file
    - [x] assign each result their 'mal id' (provided by api)  
    - [x] assign each anime's art cover, score, air date, and genre to their own variables
- [x]  when user clicks on magnifying glass, make GET request with user's input.
- [x]  Add "search result" message at the top of the page with the user's input
- [x]  create a 'view more' button at the bottom of page
    - [x]  display a certain number of titles on first search
    - [x]  when user clicks 'view more' more titles are displayed
    - [x]  when no more titles are available, remove more button is removed
- [x]  Add functionality to home button to clear search results and redisplay welcome message
- [x]  Remove unnecessary CSS
- [x]  Test functions for any errors
