### ISSUE TITLE
Design Update: Carousel

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#15]
## ⚙️ Feature

Carousel and artwork redesign

## 🖼️ Wireframes

mobile
![image](https://user-images.githubusercontent.com/48267398/157351109-10eb3c71-6bb6-475a-9581-54098ef53783.png)

desktop
![image](https://user-images.githubusercontent.com/48267398/157351315-4f161596-11f0-4f4b-b0a5-ad2fc526f2e8.png)

## ✅ Task List

- [x] create a rounded container for all artwork with a blue accented border
- [x] remove the shadow and title from the cover artwork in the carousel
- [x] when user hovers over the anime in carousel, title pops up underneath the artwork
