### ISSUE TITLE
User can click on a title to view full detail of that anime

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#2]
## 📐 Functionality

User can click on an anime title from their search query and a new page will display more detailed information about that anime.  Details will show a larger picture of the cover art, a synopsis, and a series of other additional information related to the anime

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/156667966-0c490af6-fb54-4e61-8e94-1fa566c56b87.png)
![image](https://user-images.githubusercontent.com/48267398/156667991-a98983f9-fa66-4bcf-afd1-40a19e69bd3f.png)

## ✅ Task List

- [x] Create CSS template for detailed view of anime
   - [x] Create title that is displayed on the top of the page
   - [x] Image container that takes up left half of screen
   - [x] create div that holds rating card and text content for ranking, popularity, air date, episodes, and genres
   - [x] create rating card that displays rating inside a frame
   - [x] create synopsis container that holds the synopsis
- [x] Add anchor tags to all image and title items to the DOM tree function
- [x] Add an event listener that takes an anime's data when clicked
- [x] create function that replaces CSS template's information with the selected anime's data
- [x] create function that hides the search results when an anime is clicked
- [x] create function that hides the detailed view when new anime is searched or home button is pressed
- [x] make sure feature looks nice on both mobile and desktop
- [x] get rid of all unnecessary CSS
- [x] test feature for any errors/bugs
