### ISSUE TITLE
Bug: Slow Network Requests

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#20]
## 🐛 Bug

The app should only load the content when an anime is clicked on and clear the anime view when any other view is clicked on

#### Actual Behavior

If a user clicks on the home button or favorite list button while the get request is still loading, the home screen/favorite screen will show and then content for the anime is loaded below when the get request is finished.

![slow-internet-swap-fav](https://user-images.githubusercontent.com/48267398/158006121-209a12b6-fc42-4c08-8f1d-07f3c55df96a.gif)
![slow-internet-swap-home](https://user-images.githubusercontent.com/48267398/158006122-98bbe63f-96ba-47f9-94f9-da7def1567db.gif)

#### Steps to Reproduce

To trigger the bug you must have slow internet and swap views before the get request is completed

## ✅ Task List

- [x] add a 'view' attribute to each view
   - [x] add 'view' to home page view and set it to 'home-page'
   - [x] add 'view' to the list view and set it to 'list-view'
   - [x] add 'view' to the detailed view and set it to 'detail-view'
- [x] add 'view' into data model
- [x] when user switches views, set data.view to that new view
    - [x] when user clicks on home button, set data.view to 'home-page'
    - [x] when user submits a search query, set data.view to 'list-view'
    - [x] when user clicks on a title to view details, set data.view to 'detail-view'
    - [x] when user clicks on their favorites list, set data.view to 'favorite-view'
- [x] for the loadXML() function, add a conditional statement that checks if the current view is 'list-view' after the response from the server is received.  If the current view is 'list-view' proceed with the DOM tree creation for each result, if it is not the view, do nothing
- [x] for the getDetailsById() function add a conditional statement that checks if the current view is 'detail-view' after the response from the server is received.  If the current view is 'detail' proceed with code that removes the 'hidden' class and loads the content onto the page.
- [x] prevent user from making another submit request while page is loading

**Comment by luc-ky-khuu** [comment]
![ajax-network-fix](https://user-images.githubusercontent.com/48267398/159384185-a76245ae-a9fe-4d7c-9717-fb62086154ea.gif)
![ajax-network-fix-2](https://user-images.githubusercontent.com/48267398/159384188-e5b6dd66-8cdd-47fd-82d4-3add91133508.gif)
