### ISSUE TITLE
User can see a carousel of top anime on their home page

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#22]
## ⚙️ Feature

User will see a carousel that auto scrolls with top anime on their home page

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create div that will hold the carousel on the home page section
- [ ] query for the home page carousel div
- [ ] when make get request for top anime and display to the home page
