### ISSUE TITLE
User can view trailer/promo video of anime

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#3]
## 📐 Functionality

User can view a trailer for an anime in the anime's detailed view.  Clicking on the trailer will play the trailer in the same window

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/156668071-c25ca286-2479-41ad-938c-2e04adf75b5d.png)
![image](https://user-images.githubusercontent.com/48267398/156668098-50a1a150-90a8-4a67-b2a8-8d8c891c4f9f.png)

## ✅ Task List

- [x] Create DIV for the video in the HTML skeleton
- [x] target the embed video URL in the anime data object and store it within a variable
- [x] insert the URL into the video div
- [x] make video only play when user clicks on it
- [x] make sure page looks nice on both desktop and mobile
- [x] remove unnecessary CSS
- [x] test the page for any bugs
