### ISSUE TITLE
User can view a list of related anime at the bottom of the page

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#4]
## 📐 Functionality

User can view a carousel of recommended anime titles at the bottom of the anime's detailed view page.  Clicking on the arrows will display more recommended anime from a list.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/156825217-675bbbf7-36d8-4bce-9a20-d1b5817505e0.png)
![image](https://user-images.githubusercontent.com/48267398/156825259-e65d00a2-3df4-4ba6-aee9-6466f1288231.png)

## ✅ Task List

- [x] create an HTTP request for an anime's recommended list when a user clicks on an anime title
- [x] store the data into an object in the data model
- [x] add a div to the bottom of the details page to act as a carousel that will hold the recommended list
- [x] create five columns to hold the first five anime art covers
- [x] display the first five anime art covers in the carousel from left to right
- [x] add left and right buttons that will allow the user to cycle through the list
- [x] add an event listener to the right button that displays the next five anime when clicked
- [x] add an event listener to the left button that displays the previous five anime when clicked
- [x] add the anime titles below each art cover
- [x] when user clicks on recommended, new page showing that anime detail displays
- [x] when recommended list has only 5 or less recommended, remove buttons that cycle list
- [x] when no recommended anime are available, hide recommended
- [x] check that carousel looks good on both desktop and mobile
- [x] remove any unnecessary CSS
- [x] test the feature for any bugs.
