### ISSUE TITLE
User can add anime to a favorites list

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#5]
## 📐 Functionality

User will now have a button that allows them to add an anime to a favorite list.  Adding the anime will display a new button that indicates that the anime has been added.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/48267398/156828837-42c2c992-473d-4769-b438-ddb6b13bca33.png)
![image](https://user-images.githubusercontent.com/48267398/156828887-669d71dd-1ee7-4627-ae38-7cac97c84d28.png)

## ✅ Task List

- [x] create button that displays the option to add an item to favorites list that sits on the top right corner of rating card area
- [x] create another button that will display if an anime is in the favorites list
- [x] make function that swaps 'add to favorites' button to 'favorited' button when user clicks on 'add to favorites' button
- [x] create an array that will hold the favorites list
- [x] when user clicks on 'add to favorites' button, add the anime's id number to the favorited array
- [x] only add the anime to the favorites list once
- [x] create function in the data object that stores the data function to the local storage
- [x] when user clicks on an anime from their search, check if anime is in their favorite list and display the 'favorited' button
- [x] check that page looks good on both desktop and mobile
- [x]  remove any unnecessary CSS
- [x]  test the feature for any bugs.
