### ISSUE TITLE
User can view their favorites list

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#6]
## 📐 Functionality

User now has a button that will show them a list of their favorited anime titles

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/156854873-e1d8028e-f9e7-4f20-adce-143285c36f09.png)
![image](https://user-images.githubusercontent.com/48267398/156854890-f9c9f0a2-5be3-4b34-ac06-d8b5518e3f52.png)

## ✅ Task List

- [x] create button next to search bar whose function will later display the favorites list
- [x] create function that:
   - [x] loops through the favorites list
   - [x] makes a get request for each item using their id
   - [x] display each item similar to how a regular search result looks
- [x] add an event listener to the favorites list button to trigger the previous function
- [x] clear list when user searches new anime
- [x] clear list when user presses home button
- [x] make sure user can view details of anime when anime is clicked from favorites
