### ISSUE TITLE
User can delete anime from their favorite list

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/anime-search#7]
## 📐 Functionality

User now has a button that allows them to remove a selected anime title from their favorite list.  Clicking the remove button will prompt the user to confirm removal of that title.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/157338568-d0b82bc1-8347-4d9c-9bbe-46c90ffccea8.png)
![image](https://user-images.githubusercontent.com/48267398/157338815-213120d9-2546-4615-a350-2f5206b0549f.png)

## ✅ Task List

- [x] User can see an 'edit' button on each 'favorite list' item.
- [x] only show 'edit' button when user clicks on 'favorite list' item
- [x] add event listener for edit button
- [x] create modal that has a 'cancel' and 'remove' button
- [x] when user clicks 'cancel' hide the modal
- [x] when user clicks on 'edit' button, modal pops up that confirms if user would like to delete item from favorite list
- [x] when user clicks 'remove', the selected favorite item is removed from the favorite list array
- [x] when user clicks on 'remove' the selected favorite item is also removed from the DOM.
- [x] when user clicks on 'remove' hide the modal
- [x] check code for any bugs
- [x] remove any unnecessary CSS
